$ANSIBLE_VAULT;1.1;AES256
62346230656534643061336533363939353431353338356235616130396266383135633037656266
6131383131616539666339636432613536666338353939300a343239643031303839356666666366
65663162383565326438643066653539353637333735393334343265306261306237643263633537
3037363265616564620a333535303965353464396261373562633038316463303262396434313536
37623135633834336465326539373130366561313336393035613330616532353331316461643331
38633735623766386162363539306262323765313636313337336331353233623738333235373966
30616237386532626464663534666361313335323361313161333631626237623130616261663930
36393538376463613136636433333666663830313163666638303962333261363466636163613061
3439
